import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  // ── Tela de Busca ────────────────────────────────────────────
  barraDeBusca: { flexDirection: 'row', margin: 16, marginTop: 8, height: 48 },
  botaoVoltarBusca: {
    width: 48,
    backgroundColor: '#ebebeb',
    borderTopLeftRadius: 8,
    borderBottomLeftRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  campoDeBusca: {
    flex: 1,
    backgroundColor: '#ebebeb',
    paddingHorizontal: 12,
    fontSize: 16,
  },
  botaoFiltroBusca: {
    width: 48,
    backgroundColor: '#ebebeb',
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rotuloSecao: {
    paddingHorizontal: 16,
    paddingBottom: 4,
    fontSize: 12,
    fontWeight: '500',
    color: '#555',
  },

  // ── Cards de Locais ──────────────────────────────────────────
  card: {
    flexDirection: 'row',
    backgroundColor: '#f5f5f5',
    borderRadius: 8,
    overflow: 'hidden',
  },
  imagemDoCard: { width: 80, height: 80 },
  textoDoCard: { flex: 1, padding: 12, justifyContent: 'center' },
  nomeDoLocal: { fontSize: 15, fontWeight: '600', color: '#000' },
  infoDoLocal: { fontSize: 12, color: '#555', marginTop: 4 },

  // ── Botões Flutuantes do Mapa ────────────────────────────────
  botaoBusca: {
    position: 'absolute',
    top: 16,
    left: 16,
    width: 48,
    height: 48,
    backgroundColor: 'white',
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 4,
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  botaoFiltro: {
    position: 'absolute',
    top: 16,
    right: 16,
    width: 48,
    height: 48,
    backgroundColor: 'white',
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 4,
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  etiqueta: {
    position: 'absolute',
    top: 74,
    alignSelf: 'center',
    left: '25%',
    backgroundColor: '#6393F2',
    borderRadius: 20,
    paddingVertical: 4,
    paddingHorizontal: 16,
    elevation: 4,
  },
  textoEtiqueta: { color: 'white', fontSize: 13, fontWeight: '500' },

  // ── Card do Local Selecionado (Mapa) ─────────────────────────
  cardLocal: {
    position: 'absolute',
    bottom: 72,
    left: 12,
    right: 12,
    backgroundColor: 'white',
    borderRadius: 16,
    flexDirection: 'row',
    overflow: 'hidden',
    elevation: 8,
    shadowColor: '#000',
    shadowOpacity: 0.18,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
  },
  imagemLocal: { width: 90, height: 90 },
  nomeLocal: { fontSize: 15, fontWeight: '600', color: '#000' },
  infoLocal: { fontSize: 12, color: '#555', marginTop: 4 },

  // ── Tela do Local ────────────────────────────────────────────
  localImagem: { width: '100%', height: 280 },
  botaoVoltar: {
    position: 'absolute',
    top: 54,
    left: 19,
    width: 50,
    height: 50,
    backgroundColor: 'white',
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 4,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  localConteudo: { padding: 20 },
  localNome: { fontSize: 20, fontWeight: '700', color: '#000', flex: 1 },
  localDescricao: { fontSize: 14, color: '#555', lineHeight: 22 },
  tag: {
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 12,
    borderWidth: 1,
  },
  tagTexto: { fontSize: 12, fontWeight: '500' },

  // ── Modal de Filtro ──────────────────────────────────────────
  fundo: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  painel: {
    backgroundColor: 'white',
    borderRadius: 16,
    padding: 20,
    paddingBottom: 36,
  },
  painelCabecalho: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  botaoX: {
    width: 35,
    height: 35,
    backgroundColor: '#f0f0f0',
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tituloPainel: { fontSize: 18, fontWeight: '700' },
  labelFiltro: {
    fontSize: 15,
    fontWeight: '600',
    marginBottom: 10,
    color: '#333',
  },
  opcao: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: '#ccc',
  },
  opcaoAtiva: { borderColor: '#6393F2', backgroundColor: '#e8eeff' },
  textoOpcao: { fontSize: 13, fontWeight: '500', color: '#333' },

  // ── Barra de Navegação ───────────────────────────────────────
  navBar: { height: 64, backgroundColor: '#f3edf7', flexDirection: 'row' },
  itemNav: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 2 },
  pastilhaNav: {
    width: 56,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pastilhaNavAtiva: { backgroundColor: '#e8def8' },
  rotuloNav: { fontSize: 11, fontWeight: '500' },

  // ── Telas Simples ────────────────────────────────────────────
  telaCentral: {
    flex: 1,
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  tituloTela: { fontSize: 16, fontWeight: '500', color: '#625b71' },
  subTituloTela: { fontSize: 13, color: '#999' },
});
