import { StyleSheet } from 'react-native';
import { feedStyles } from './features/feedStyles';
import { mapStyles } from './features/mapStyles';
import { perfilStyles } from './features/perfilStyles';
import { searchStyles } from './features/searchStyles';
import { notificationStyles } from './features/notificationStyles';
import { createStyles } from './features/createStyles';
import { messageStyles } from './features/messageStyles';
import { colors, spacing, radii } from './tokens';

const baseStyles = {
  card: {
    flexDirection: 'row',
    backgroundColor: '#f5f5f5',
    borderRadius: 8,
    overflow: 'hidden',
  },
  cardImage: { width: 80, height: 80 },
  cardText: { flex: 1, padding: 12, justifyContent: 'center' },
  cardTitle: { fontSize: 15, fontWeight: '600', color: colors.black },
  cardInfo: { fontSize: 12, color: colors.textSecondary, marginTop: 4 },
  selectedPlaceCard: {
    backgroundColor: colors.white,
    borderRadius: 16,
    flexDirection: 'row',
    overflow: 'hidden',
    elevation: 8,
    shadowColor: '#000',
    shadowOpacity: 0.18,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
  },
  selectedPlaceImage: { width: 90, height: 90 },
  selectedPlaceTitle: { fontSize: 15, fontWeight: '600', color: colors.black },
  selectedPlaceInfo: { fontSize: 12, color: colors.textSecondary, marginTop: 4 },
  detailImage: { width: '100%', height: 280 },
  backButtonOnDetail: {
    position: 'absolute',
    top: 54,
    left: 19,
    width: 50,
    height: 50,
    backgroundColor: colors.white,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 4,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  detailContent: { padding: 20 },
  detailTitle: { fontSize: 20, fontWeight: '700', color: colors.black, flex: 1 },
  detailDescription: { fontSize: 14, color: colors.textSecondary, lineHeight: 22 },
  tag: {
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 12,
    borderWidth: 1,
  },
  tagText: { fontSize: 12, fontWeight: '500' },
  overlay: {
    flex: 1,
    backgroundColor: colors.overlay,
    justifyContent: 'flex-end',
  },
  panel: {
    backgroundColor: colors.white,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    padding: 20,
    paddingBottom: 36,
    maxHeight: '80%',
  },
  panelHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  closeButton: {
    width: 35,
    height: 35,
    backgroundColor: '#f0f0f0',
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  panelTitle: { fontSize: 18, fontWeight: '700' },
  filterLabel: {
    fontSize: 15,
    fontWeight: '600',
    marginBottom: 10,
    color: '#333',
  },
  optionChip: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: '#ccc',
  },
  optionChipActive: { borderColor: colors.purple, backgroundColor: colors.purpleLight },
  optionChipText: { fontSize: 13, fontWeight: '500', color: colors.textPrimary },
  optionChipTextActive: { color: colors.purple, fontWeight: '600' },
  panelTitlePurple: { fontSize: 18, fontWeight: '700', color: colors.purple },
  panelClearText: { fontSize: 13, color: colors.purple, fontWeight: '600' },
  centeredScreen: {
    flex: 1,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  screenTitle: { fontSize: 18, fontWeight: '700', color: colors.purple },
  screenSubtitle: { fontSize: 13, color: colors.textSecondary, marginTop: spacing.xs },
  tabBar: {
    height: 72,
    backgroundColor: colors.navBackground,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingBottom: 4,
  },
  tabBarItem: { alignItems: 'center', justifyContent: 'center', gap: 2, minWidth: 56 },
  tabPill: {
    width: 48,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabPillActive: { backgroundColor: colors.navActivePill },
  tabPillCreate: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: colors.purple,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: -20,
    elevation: 6,
    shadowColor: colors.purple,
    shadowOpacity: 0.35,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
  },
  tabLabel: { fontSize: 11, fontWeight: '500', color: colors.textSecondary },
  tabLabelActive: { color: colors.purple, fontWeight: '700' },
  authScreen: { flex: 1, backgroundColor: colors.white },
  authCenter: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.xl,
  },
  authCard: {
    width: '100%',
    maxWidth: 380,
    backgroundColor: colors.purple,
    borderRadius: 18,
    padding: 22,
    paddingTop: 26,
    elevation: 10,
    shadowColor: '#000',
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
  },
  authTitle: {
    fontSize: 26,
    fontWeight: '800',
    letterSpacing: 1,
    color: '#1C052C',
    marginBottom: 6,
  },
  authSubtitle: {
    fontSize: 16,
    letterSpacing: 2,
    color: '#1C052C',
    marginBottom: 18,
  },
  authInput: {
    height: 48,
    backgroundColor: colors.white,
    borderRadius: 8,
    paddingHorizontal: spacing.lg,
    fontSize: 14,
    color: '#1C052C',
    marginBottom: spacing.md,
  },
  authButton: {
    height: 50,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2A0648',
    marginTop: 6,
  },
  authButtonText: { color: colors.white, fontSize: 16, fontWeight: '500' },
  authLinks: { marginTop: 14, gap: 10 },
  authLink: {
    color: 'rgba(255,255,255,0.92)',
    fontSize: 13,
    fontWeight: '599',
    textAlign: 'center',
  },
};

export default StyleSheet.create({
  ...baseStyles,
  ...searchStyles,
  ...mapStyles,
  ...perfilStyles,
  ...feedStyles,
  ...notificationStyles,
  ...createStyles,
  ...messageStyles,
});
