import { StyleSheet } from 'react-native';
import { mapStyles } from './features/mapStyles';
import { searchStyles } from './features/searchStyles';
import { colors } from './tokens';

const baseStyles = {
  card: {
    flexDirection: 'row',
    backgroundColor: '#f5f5f5',
    borderRadius: 8,
    overflow: 'hidden',
  },
  cardImage: { width: 80, height: 80 },
  cardText: { flex: 1, padding: 12, justifyContent: 'center' },
  cardTitle: { fontSize: 15, fontWeight: '600', color: colors.black },
  cardInfo: { fontSize: 12, color: colors.textSecondary, marginTop: 4 },
  filterTag: {
    position: 'absolute',
    top: 74,
    alignSelf: 'center',
    left: '25%',
    backgroundColor: colors.primary,
    borderRadius: 20,
    paddingVertical: 4,
    paddingHorizontal: 16,
    elevation: 4,
  },
  filterTagText: { color: colors.white, fontSize: 13, fontWeight: '500' },
  selectedPlaceCard: {
    position: 'absolute',
    bottom: 72,
    left: 12,
    right: 12,
    backgroundColor: colors.white,
    borderRadius: 16,
    flexDirection: 'row',
    overflow: 'hidden',
    elevation: 8,
    shadowColor: '#000',
    shadowOpacity: 0.18,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
  },
  selectedPlaceImage: { width: 90, height: 90 },
  selectedPlaceTitle: { fontSize: 15, fontWeight: '600', color: colors.black },
  selectedPlaceInfo: { fontSize: 12, color: colors.textSecondary, marginTop: 4 },
  detailImage: { width: '100%', height: 280 },
  backButtonOnDetail: {
    position: 'absolute',
    top: 54,
    left: 19,
    width: 50,
    height: 50,
    backgroundColor: colors.white,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 4,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  detailContent: { padding: 20 },
  detailTitle: { fontSize: 20, fontWeight: '700', color: colors.black, flex: 1 },
  detailDescription: { fontSize: 14, color: colors.textSecondary, lineHeight: 22 },
  tag: {
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 12,
    borderWidth: 1,
  },
  tagText: { fontSize: 12, fontWeight: '500' },
  overlay: {
    flex: 1,
    backgroundColor: colors.overlay,
    justifyContent: 'flex-end',
  },
  panel: {
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 20,
    paddingBottom: 36,
  },
  panelHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  closeButton: {
    width: 35,
    height: 35,
    backgroundColor: '#f0f0f0',
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  panelTitle: { fontSize: 18, fontWeight: '700' },
  filterLabel: {
    fontSize: 15,
    fontWeight: '600',
    marginBottom: 10,
    color: '#333',
  },
  optionChip: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: '#ccc',
  },
  optionChipActive: { borderColor: colors.primary, backgroundColor: '#e8eeff' },
  optionChipText: { fontSize: 13, fontWeight: '500', color: '#333' },
  centeredScreen: {
    flex: 1,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  screenTitle: { fontSize: 16, fontWeight: '500', color: '#625b71' },
  screenSubtitle: { fontSize: 13, color: '#999' },
  tabBar: { height: 64, backgroundColor: colors.navBackground },
  tabBarItem: { alignItems: 'center', justifyContent: 'center', gap: 2 },
  tabPill: {
    width: 56,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabPillActive: { backgroundColor: colors.navActivePill },
  tabIcon: { fontSize: 22 },
  tabLabel: { fontSize: 11, fontWeight: '500', color: '#49454f' },
  tabLabelActive: { color: '#625b71' },
};

export default StyleSheet.create({
  ...baseStyles,
  ...searchStyles,
  ...mapStyles,
});
