import { colors, spacing, radii } from '../tokens';

export const authStyles = {
  authScreen: { flex: 1, backgroundColor: colors.white },
  authCenter: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.xl,
  },
  authScrollContent: {
    flexGrow: 1,
    paddingHorizontal: spacing.lg,
  },
  authPressableArea: {
    flexGrow: 1,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.lg,
  },
  authPressableAreaKeyboard: {
    justifyContent: 'flex-start',
    paddingTop: spacing.sm,
    paddingBottom: spacing.xl * 3,
  },
  authHero: {
    alignItems: 'center',
    paddingBottom: spacing.lg,
  },
  authLogoCircle: {
    width: 112,
    height: 112,
    borderRadius: 56,
    backgroundColor: colors.purpleMuted,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: colors.purpleLight,
    overflow: 'hidden',
  },
  authLogo: {
    width: 88,
    height: 88,
  },
  authBrandTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: colors.purple,
    marginTop: spacing.md,
  },
  authBrandSubtitle: {
    fontSize: 13,
    color: colors.textSecondary,
    marginTop: spacing.xs,
    textAlign: 'center',
    lineHeight: 18,
    paddingHorizontal: spacing.md,
  },
  authCard: {
    width: '100%',
    maxWidth: 380,
    backgroundColor: colors.white,
    borderRadius: radii.lg,
    borderWidth: 1.5,
    borderColor: colors.purpleLight,
    padding: spacing.lg,
    paddingTop: spacing.xl,
    elevation: 4,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
  },
  authTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: colors.textPrimary,
    marginBottom: spacing.xs,
  },
  authSubtitle: {
    fontSize: 14,
    color: colors.textSecondary,
    marginBottom: spacing.lg,
    lineHeight: 20,
  },
  authHint: {
    fontSize: 13,
    color: colors.textSecondary,
    lineHeight: 18,
    marginBottom: spacing.md,
  },
  authInput: {
    minHeight: 48,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing.md,
    fontSize: 15,
    color: colors.textPrimary,
    backgroundColor: colors.purpleMuted,
    marginBottom: spacing.md,
  },
  authButton: {
    height: 52,
    borderRadius: radii.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.purple,
    marginTop: spacing.sm,
  },
  authButtonText: {
    color: colors.textOnPurple,
    fontSize: 16,
    fontWeight: '700',
  },
  authLinks: {
    marginTop: spacing.lg,
    gap: spacing.sm,
    alignItems: 'center',
  },
  authLink: {
    color: colors.purple,
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },
};
