import { colors, spacing, radii } from '../tokens';

export const createStyles = {
  createScreen: {
    flex: 1,
    backgroundColor: colors.white,
  },
  createScroll: {
    flexGrow: 1,
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.xl * 3,
  },
  createHero: {
    alignItems: 'center',
    paddingTop: spacing.xl,
    paddingBottom: spacing.lg,
  },
  createMascotCircle: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: colors.purpleMuted,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: colors.purpleLight,
  },
  createTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: colors.purple,
    marginTop: spacing.lg,
    textAlign: 'center',
  },
  createSubtitle: {
    fontSize: 14,
    color: colors.textSecondary,
    marginTop: spacing.sm,
    textAlign: 'center',
    lineHeight: 20,
    paddingHorizontal: spacing.md,
  },
  createOptionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: radii.lg,
    borderWidth: 1.5,
    borderColor: colors.purple,
    padding: spacing.lg,
    marginBottom: spacing.md,
    gap: spacing.md,
  },
  createOptionIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.purpleMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  createOptionTextBlock: {
    flex: 1,
  },
  createOptionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  createOptionHint: {
    fontSize: 13,
    color: colors.textSecondary,
    marginTop: 4,
    lineHeight: 18,
  },
  createPrimaryBtn: {
    marginTop: spacing.md,
    height: 52,
    borderRadius: radii.pill,
    backgroundColor: colors.purple,
    alignItems: 'center',
    justifyContent: 'center',
  },
  createPrimaryBtnText: {
    color: colors.textOnPurple,
    fontSize: 16,
    fontWeight: '700',
  },

  createLocalScreen: {
    flex: 1,
    backgroundColor: colors.white,
  },
  createLocalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  createLocalBackBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: colors.purple,
    alignItems: 'center',
    justifyContent: 'center',
  },
  createLocalHeaderTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: colors.purple,
  },
  createLocalHeaderSpacer: {
    width: 40,
  },
  createLocalScroll: {
    padding: spacing.lg,
    paddingBottom: spacing.xl * 3,
    gap: spacing.lg,
  },
  createLocalFieldLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: spacing.sm,
  },
  createLocalInput: {
    minHeight: 48,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing.md,
    fontSize: 15,
    color: colors.textPrimary,
    backgroundColor: colors.purpleMuted,
  },
  createLocalInputMultiline: {
    minHeight: 96,
    paddingTop: spacing.md,
    textAlignVertical: 'top',
  },
  createLocalChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  createLocalChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: radii.pill,
    borderWidth: 1.5,
    borderColor: colors.border,
    backgroundColor: colors.white,
  },
  createLocalChipActive: {
    borderColor: colors.purple,
    backgroundColor: colors.purpleLight,
  },
  createLocalChipLabel: {
    fontSize: 13,
    fontWeight: '500',
    color: colors.textSecondary,
  },
  createLocalChipLabelActive: {
    color: colors.purple,
    fontWeight: '700',
  },
  createLocalPreview: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    padding: spacing.md,
    borderRadius: radii.lg,
    backgroundColor: colors.purpleMuted,
    borderWidth: 1,
    borderColor: colors.purpleLight,
  },
  createLocalPreviewEmoji: {
    fontSize: 32,
  },
  createLocalPreviewText: {
    flex: 1,
    fontSize: 13,
    color: colors.textSecondary,
    lineHeight: 18,
  },
  createLocalFooter: {
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },

  createPartidaDateBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    minHeight: 48,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing.md,
    backgroundColor: colors.purpleMuted,
  },
  createPartidaDateText: {
    fontSize: 15,
    color: colors.textPrimary,
    fontWeight: '500',
  },
  createPartidaDateConfirm: {
    marginTop: spacing.sm,
    alignSelf: 'flex-end',
  },
  createPartidaDateConfirmText: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.purple,
  },
  createPartidaEmpty: {
    fontSize: 14,
    color: colors.textSecondary,
    textAlign: 'center',
    paddingVertical: spacing.lg,
  },
  createPartidaPlaceCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    padding: spacing.sm,
    marginBottom: spacing.sm,
    borderRadius: radii.lg,
    borderWidth: 1.5,
    borderColor: colors.border,
    backgroundColor: colors.white,
  },
  createPartidaPlaceCardActive: {
    borderColor: colors.purple,
    backgroundColor: colors.purpleLight,
  },
  createPartidaPlaceImage: {
    width: 64,
    height: 64,
    borderRadius: radii.md,
    backgroundColor: colors.purpleMuted,
  },
  createPartidaPlaceBody: {
    flex: 1,
  },
  createPartidaPlaceName: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  createPartidaPlaceMeta: {
    fontSize: 12,
    color: colors.textSecondary,
    marginTop: 2,
  },
  createPartidaLimiteRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    marginTop: spacing.sm,
  },
  createPartidaLimiteBtn: {
    alignItems: 'center',
    backgroundColor: colors.purpleMuted,
    borderColor: colors.border,
    borderRadius: radii.md,
    borderWidth: 1,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  createPartidaLimiteValor: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: '700',
    minWidth: 48,
    textAlign: 'center',
  },
  createLocalAddressGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    justifyContent: 'space-between',
  },
  createLocalAddressHalf: {
    width: '48%',
  },
  createLocalMapBox: {
    height: 200,
    borderRadius: radii.md,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: spacing.sm,
  },
  createLocalMapHint: {
    fontSize: 12,
    color: colors.textSecondary,
    marginBottom: spacing.sm,
    lineHeight: 16,
  },
};
