import { StyleSheet } from 'react-native';
import { colors, spacing, radii } from '../tokens';

export const mapStyles = {
  mapTopOverlayAbsolute: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 10,
    paddingTop: spacing.sm,
    paddingHorizontal: spacing.lg,
    gap: spacing.sm,
  },
  mapBottomCardOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 10,
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.sm,
  },
  mapTopOverlay: {
    gap: spacing.sm,
  },
  mapSearchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  mapSearchBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: radii.pill,
    borderWidth: 1.5,
    borderColor: colors.purple,
    paddingHorizontal: spacing.lg,
    height: 48,
    elevation: 4,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
  },
  mapChipsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: spacing.sm,
  },
  mapActiveFilterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    backgroundColor: colors.purple,
    borderRadius: radii.pill,
    paddingVertical: 6,
    paddingLeft: spacing.md,
    paddingRight: spacing.sm,
    maxWidth: '100%',
  },
  mapActiveFilterChipText: {
    color: colors.textOnPurple,
    fontSize: 13,
    fontWeight: '600',
    flexShrink: 1,
  },
  mapClearAllChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: radii.pill,
    borderWidth: 1.5,
    borderColor: colors.purple,
    paddingVertical: 6,
    paddingHorizontal: spacing.md,
  },
  mapClearAllChipText: {
    color: colors.purple,
    fontSize: 13,
    fontWeight: '700',
  },
  selectedPlaceCardWrap: {
    position: 'relative',
  },
  selectedPlaceCardPressable: {
    flex: 1,
  },
  selectedPlaceCardBody: {
    flex: 1,
    padding: spacing.md,
    justifyContent: 'center',
  },
  selectedPlaceCloseBtn: {
    padding: spacing.md,
    alignSelf: 'center',
  },
  selectedPlaceCloseBtnFloating: {
    position: 'absolute',
    top: -6,
    right: -6,
    backgroundColor: colors.white,
    borderRadius: 14,
    zIndex: 2,
  },
  mapFilterButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.white,
    borderWidth: 1.5,
    borderColor: colors.purple,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 3,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  mapFilterButtonActive: {
    backgroundColor: colors.purpleLight,
  },
  mapSearchPlaceholder: {
    flex: 1,
    marginLeft: spacing.sm,
    fontSize: 15,
    color: colors.textSecondary,
  },
  floatingButtonLeft: {
    position: 'absolute',
    top: 16,
    left: 16,
    width: 48,
    height: 48,
    backgroundColor: colors.white,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 4,
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  floatingButtonRight: {
    position: 'absolute',
    top: 72,
    right: 16,
    width: 48,
    height: 48,
    backgroundColor: colors.white,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 4,
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  selectedPlaceCta: {
    fontSize: 11,
    color: colors.purple,
    marginTop: 4,
    fontWeight: '600',
  },
};
