import { Platform, StyleSheet } from 'react-native';
import { colors, radii, spacing } from '../tokens';

export const perfilStyles = {
  usuarioScreen: { flex: 1, backgroundColor: colors.white },
  usuarioTopRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
  },
  usuarioIconBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: colors.purple,
    alignItems: 'center',
    justifyContent: 'center',
  },
  usuarioIconBtnTextPlus: { fontSize: 22, color: colors.purple, fontWeight: '600' },
  usuarioIconBtnTextMenu: { fontSize: 18, color: colors.purple, fontWeight: '700' },
  usuarioAvatarWrap: { alignSelf: 'center', marginTop: spacing.xs },
  usuarioAvatar: {
    width: 112,
    height: 112,
    borderRadius: 56,
    backgroundColor: colors.purpleMuted,
    borderWidth: 3,
    borderColor: colors.purpleLight,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  usuarioAvatarEmoji: { fontSize: 56 },
  usuarioEditBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.purple,
    alignItems: 'center',
    justifyContent: 'center',
  },
  usuarioAvatarImage: { width: '100%', height: '100%', borderRadius: 56 },
  usuarioFotoAcoesRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: spacing.md,
    columnGap: spacing.md,
  },
  usuarioFotoSalvarBtn: {
    paddingVertical: 10,
    paddingHorizontal: spacing.lg,
    borderRadius: radii.md,
    backgroundColor: colors.purple,
  },
  usuarioFotoSalvarBtnText: { color: colors.textOnPurple, fontSize: 14, fontWeight: '600' },
  usuarioFotoCancelarBtn: {
    paddingVertical: 10,
    paddingHorizontal: spacing.lg,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.purple,
    backgroundColor: colors.white,
  },
  usuarioFotoCancelarBtnText: { color: colors.purple, fontSize: 14, fontWeight: '600' },
  usuarioName: {
    marginTop: spacing.md,
    textAlign: 'center',
    fontSize: 20,
    fontWeight: '700',
    color: colors.purple,
  },
  usuarioLocationRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: spacing.xs,
  },
  usuarioLocationText: { fontSize: 13, color: colors.textSecondary },
  usuarioTagsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginTop: spacing.md,
    paddingHorizontal: spacing.lg,
    columnGap: spacing.sm,
    rowGap: spacing.sm,
  },
  usuarioTagPill: {
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.purple,
    backgroundColor: colors.purpleMuted,
  },
  usuarioTagText: { fontSize: 12, fontWeight: '600', color: colors.purple },
  usuarioStatsRow: { flexDirection: 'row', justifyContent: 'center', marginTop: spacing.xl, columnGap: 56 },
  usuarioStatBlock: { alignItems: 'center' },
  usuarioStatBlockPressable: { alignItems: 'center', paddingVertical: spacing.xs, paddingHorizontal: spacing.md },
  usuarioStatValue: { fontSize: 18, fontWeight: '700', color: colors.purple },
  usuarioStatLabel: { fontSize: 12, color: colors.textSecondary, marginTop: 2 },

  perfilOutroTopBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  perfilOutroTopTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 16,
    fontWeight: '700',
    color: colors.purple,
    marginHorizontal: spacing.sm,
  },
  perfilOutroAvatarLetter: { fontSize: 44, fontWeight: '700', color: colors.purple },
  perfilOutroBio: {
    fontSize: 13,
    color: colors.textSecondary,
    textAlign: 'center',
    marginTop: spacing.sm,
    paddingHorizontal: spacing.xl,
    lineHeight: 18,
  },
  perfilOutroFollowBtn: {
    alignSelf: 'center',
    marginTop: spacing.lg,
    paddingVertical: 10,
    paddingHorizontal: spacing.xl * 2,
    borderRadius: 999,
    backgroundColor: colors.purple,
  },
  perfilOutroFollowBtnActive: {
    backgroundColor: colors.white,
    borderWidth: 1.5,
    borderColor: colors.purple,
  },
  perfilOutroFollowBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textOnPurple,
  },
  perfilOutroFollowBtnTextActive: {
    color: colors.purple,
  },
  usuarioTrophyBox: {
    marginHorizontal: spacing.lg,
    marginTop: spacing.xl,
    paddingVertical: spacing.xl,
    borderRadius: 12,
    backgroundColor: colors.purpleMuted,
    borderWidth: 1,
    borderColor: colors.purpleLight,
    alignItems: 'center',
  },
  usuarioTrophyEmoji: { fontSize: 40 },
  usuarioTrophyLabel: { marginTop: spacing.sm, fontSize: 14, fontWeight: '600', color: colors.purple },
  usuarioTabBar: {
    flexDirection: 'row',
    marginTop: spacing.xl,
    marginHorizontal: spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: '#eaeaea',
  },
  usuarioTabBtn: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: spacing.sm,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  usuarioTabBtnActive: { borderBottomColor: colors.purple },
  usuarioTabText: { fontSize: 13, fontWeight: '500', color: colors.textSecondary },
  usuarioTabTextActive: { fontWeight: '700', color: colors.purple },
  usuarioFeedSection: {
    marginTop: spacing.sm,
    marginBottom: spacing.xl,
    paddingHorizontal: 0,
  },
  usuarioFeedGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: '100%',
  },
  usuarioFeedCell: {
    aspectRatio: 1,
    padding: 1,
    width: '33.333%',
  },
  usuarioFeedCellInner: {
    alignItems: 'center',
    backgroundColor: colors.purpleMuted,
    flex: 1,
    justifyContent: 'center',
    overflow: 'hidden',
  },
  usuarioFeedCellImage: {
    height: '100%',
    width: '100%',
  },
  usuarioFeedCellPartida: {
    backgroundColor: colors.purpleLight,
  },
  usuarioFeedCellBadge: {
    backgroundColor: 'rgba(0,0,0,0.55)',
    borderRadius: 4,
    bottom: 4,
    left: 4,
    paddingHorizontal: 5,
    paddingVertical: 2,
    position: 'absolute',
  },
  usuarioFeedCellBadgeText: {
    color: colors.white,
    fontSize: 9,
    fontWeight: '700',
  },
  usuarioFeedCaption: {
    fontSize: 11,
    color: colors.textSecondary,
    marginTop: spacing.sm,
    paddingHorizontal: spacing.lg,
    textAlign: 'center',
  },
  instaPostOverlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.85)',
    flex: 1,
    justifyContent: 'center',
  },
  instaPostBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  instaPostCloseBtn: {
    position: 'absolute',
    right: 16,
    top: Platform.OS === 'web' ? 16 : 48,
    zIndex: 10,
  },
  instaPostCard: {
    backgroundColor: colors.white,
    borderRadius: 4,
    elevation: 12,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.35,
    shadowRadius: 24,
    zIndex: 2,
  },
  instaPostMedia: {
    backgroundColor: '#000',
    flex: 1,
    minWidth: 280,
    overflow: 'hidden',
    position: 'relative',
  },
  instaPostMediaMobile: {
    alignSelf: 'center',
    flex: 0,
    minWidth: 0,
  },
  instaPostMediaImage: {
    height: '100%',
    width: '100%',
  },
  instaPostScrollMobile: {
    flex: 1,
    width: '100%',
  },
  instaPostScrollMobileContent: {
    alignItems: 'center',
    flexGrow: 1,
    justifyContent: 'center',
    paddingVertical: spacing.xl,
  },
  instaPostPainelMobile: {
    flexShrink: 0,
    maxHeight: undefined,
  },
  instaPostVerMaisComentarios: {
    color: colors.textSecondary,
    fontSize: 13,
    marginBottom: spacing.sm,
    marginTop: spacing.xs,
  },
  perfilAcoesSheetRoot: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  perfilAcoesSheetBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.overlay,
  },
  perfilAcoesSheetCard: {
    backgroundColor: colors.white,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    paddingBottom: spacing.xl + 8,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
  },
  perfilAcoesSheetHandle: {
    alignSelf: 'center',
    backgroundColor: colors.border,
    borderRadius: 2,
    height: 4,
    marginBottom: spacing.md,
    width: 40,
  },
  perfilAcoesSheetTitulo: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '600',
    marginBottom: spacing.sm,
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  perfilAcoesSheetRow: {
    alignItems: 'center',
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: spacing.md,
    paddingVertical: spacing.lg,
  },
  perfilAcoesSheetRowText: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '600',
  },
  perfilAcoesSheetRowDanger: {
    color: '#ed4956',
  },
  perfilAcoesSheetCancel: {
    alignItems: 'center',
    marginTop: spacing.sm,
    paddingVertical: spacing.md,
  },
  perfilAcoesSheetCancelText: {
    color: colors.textSecondary,
    fontSize: 15,
    fontWeight: '600',
  },
  instaPostMediaPlaceholder: {
    alignItems: 'center',
    backgroundColor: colors.purpleMuted,
    justifyContent: 'center',
  },
  instaPostPainel: {
    backgroundColor: colors.white,
    flexDirection: 'column',
    maxHeight: 580,
  },
  instaPostHeader: {
    alignItems: 'center',
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm + 2,
  },
  instaPostHeaderUser: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: spacing.sm,
  },
  instaPostHeaderAvatar: {
    alignItems: 'center',
    backgroundColor: colors.purpleMuted,
    borderRadius: 14,
    height: 28,
    justifyContent: 'center',
    width: 28,
  },
  instaPostHeaderNome: {
    color: colors.textPrimary,
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
  },
  instaPostHeaderMenuWrap: {
    position: 'relative',
    zIndex: 20,
  },
  instaPostMenuDropdown: {
    backgroundColor: colors.white,
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: 1,
    elevation: 8,
    minWidth: 160,
    position: 'absolute',
    right: 0,
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 8,
    top: 28,
  },
  instaPostMenuItem: {
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
  },
  instaPostMenuItemLast: {
    borderBottomWidth: 0,
  },
  instaPostMenuItemText: {
    color: colors.textPrimary,
    fontSize: 14,
  },
  instaPostMenuItemDanger: {
    color: '#ed4956',
    fontWeight: '600',
  },
  instaPostMenuBackdrop: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 15,
  },
  instaPostComentariosScroll: {
    flex: 1,
    minHeight: 120,
  },
  instaPostComentariosContent: {
    paddingBottom: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
  },
  instaPostLegendaRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginBottom: spacing.md,
  },
  instaPostComentarioRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginBottom: spacing.md,
  },
  instaPostComentarioAvatar: {
    alignItems: 'center',
    backgroundColor: colors.purpleMuted,
    borderRadius: 12,
    height: 24,
    justifyContent: 'center',
    marginTop: 2,
    width: 24,
  },
  instaPostComentarioCorpo: {
    flex: 1,
  },
  instaPostComentarioTexto: {
    color: colors.textPrimary,
    fontSize: 14,
    lineHeight: 18,
  },
  instaPostComentarioAutor: {
    fontWeight: '700',
  },
  instaPostComentarioMeta: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
    marginTop: spacing.xs,
  },
  instaPostComentarioTempo: {
    color: colors.textSecondary,
    fontSize: 12,
  },
  instaPostComentarioResponder: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '600',
  },
  instaPostFooter: {
    borderTopColor: colors.border,
    borderTopWidth: 1,
    paddingBottom: Platform.OS === 'ios' ? spacing.sm : spacing.md,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
  },
  instaPostAcoes: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    marginBottom: spacing.sm,
  },
  instaPostCurtidas: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '700',
    marginBottom: spacing.xs,
  },
  instaPostData: {
    color: colors.textSecondary,
    fontSize: 11,
    letterSpacing: 0.3,
    marginBottom: spacing.sm,
    textTransform: 'uppercase',
  },
  instaPostInputRow: {
    alignItems: 'center',
    borderTopColor: colors.border,
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: spacing.sm,
    paddingTop: spacing.sm,
  },
  instaPostInput: {
    color: colors.textPrimary,
    flex: 1,
    fontSize: 14,
    paddingVertical: Platform.OS === 'web' ? 6 : 4,
  },
  instaPostPostarBtn: {
    color: colors.purple,
    fontSize: 14,
    fontWeight: '700',
  },
  usuarioEmptyTab: {
    minHeight: 120,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: spacing.xl,
  },
  usuarioEmptyTabText: { fontSize: 13, color: colors.textSecondary, textAlign: 'center' },
  perfilModalRoot: { flex: 1, justifyContent: 'center', paddingHorizontal: spacing.xl },
  perfilModalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.overlay,
  },
  perfilModalCard: { backgroundColor: colors.white, borderRadius: 16, padding: spacing.lg },
  perfilModalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.purple,
    marginBottom: spacing.sm,
  },
  perfilModalSubtitle: { fontSize: 13, color: '#888', marginBottom: spacing.md },
  perfilModalRow: { paddingVertical: spacing.md, borderTopWidth: 1, borderTopColor: '#eee' },
  perfilModalRowTitle: { fontSize: 15, fontWeight: '600', color: '#333' },
  perfilModalRowHint: { fontSize: 12, color: '#888', marginTop: 2 },
  perfilModalCloseBtn: {
    alignSelf: 'flex-end',
    marginTop: spacing.md,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.lg,
    backgroundColor: colors.purple,
    borderRadius: 8,
  },
  perfilModalCloseText: { fontSize: 14, fontWeight: '600', color: colors.textOnPurple },
  perfilModalLogoutRow: { paddingVertical: spacing.md, borderTopWidth: 1, borderTopColor: '#eee' },
  perfilModalLogoutTitle: { fontSize: 15, fontWeight: '600', color: '#c62828' },
  perfilModalLogoutHint: { fontSize: 12, color: '#888', marginTop: 2 },
  usuarioPostCard: {
    backgroundColor: colors.white,
    borderColor: '#eaeaea',
    borderRadius: 12,
    borderWidth: 1,
    marginBottom: spacing.md,
    overflow: 'hidden',
  },
  usuarioPostImage: {
    backgroundColor: colors.purpleMuted,
    height: 160,
    width: '100%',
  },
  usuarioPostBody: { padding: spacing.md },
  usuarioPostDesc: { color: colors.textPrimary, fontSize: 14, lineHeight: 20 },
  usuarioPostMeta: { color: colors.textSecondary, fontSize: 11, marginTop: spacing.xs },
  usuarioPostActions: {
    borderTopColor: '#eee',
    borderTopWidth: 1,
    flexDirection: 'row',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  usuarioPostActionBtn: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 4,
    justifyContent: 'center',
    paddingVertical: spacing.xs,
  },
  usuarioPostActionText: { color: colors.purple, fontSize: 13, fontWeight: '600' },
  usuarioPostActionDanger: { color: '#c62828' },
  usuarioPostPartidaBadge: {
    alignSelf: 'flex-start',
    backgroundColor: colors.purpleLight,
    borderRadius: radii.pill,
    marginBottom: spacing.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: 4,
  },
  usuarioPostPartidaBadgeText: { color: colors.purple, fontSize: 11, fontWeight: '700' },
  perfilScreenScroll: { flexGrow: 1, padding: spacing.lg, paddingBottom: spacing.xl * 2 },
  perfilSectionTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: colors.purple,
    marginBottom: spacing.md,
    marginTop: spacing.sm,
  },
  perfilFieldLabel: { fontSize: 12, color: '#666', marginBottom: spacing.xs, marginTop: spacing.sm },
  perfilPrimaryBtn: {
    marginTop: spacing.lg,
    height: 48,
    borderRadius: 10,
    backgroundColor: colors.purple,
    alignItems: 'center',
    justifyContent: 'center',
  },
  perfilPrimaryBtnText: { color: colors.white, fontSize: 16, fontWeight: '600' },
  perfilDivider: { height: 1, backgroundColor: '#eee', marginVertical: spacing.lg },
  perfilDangerBtn: {
    marginTop: spacing.md,
    height: 48,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#c62828',
    alignItems: 'center',
    justifyContent: 'center',
  },
  perfilDangerBtnText: { color: '#c62828', fontSize: 16, fontWeight: '600' },
  perfilHint: { fontSize: 12, color: '#888', marginTop: spacing.sm, lineHeight: 18 },
  perfilPrefRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  perfilPrefRowText: { fontSize: 15, color: '#333', flex: 1, paddingRight: spacing.md },
  perfilPrefSub: { fontSize: 12, color: '#888', marginTop: 2 },
  perfilThemeRow: {
    flexDirection: 'row',
    marginTop: spacing.sm,
    columnGap: spacing.sm,
  },
  perfilThemeChip: {
    flex: 1,
    paddingVertical: spacing.sm,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ccc',
    alignItems: 'center',
  },
  perfilThemeChipActive: { borderColor: colors.purple, backgroundColor: '#f3e8ff' },
  perfilThemeChipText: { fontSize: 14, fontWeight: '500', color: '#555' },
  perfilThemeChipTextActive: { color: colors.purple, fontWeight: '700' },
  perfilLegalBlock: { marginBottom: spacing.xl },
  perfilLegalHeading: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.purple,
    marginBottom: spacing.sm,
  },
  perfilLegalParagraph: { fontSize: 14, color: '#444', lineHeight: 22 },
};
