import { StyleSheet } from 'react-native';
import { colors, spacing } from '../tokens';

export const perfilStyles = {
  usuarioScreen: { flex: 1, backgroundColor: colors.white },
  usuarioTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
  },
  usuarioIconBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: colors.purple,
    alignItems: 'center',
    justifyContent: 'center',
  },
  usuarioIconBtnTextPlus: { fontSize: 22, color: colors.purple, fontWeight: '600' },
  usuarioIconBtnTextMenu: { fontSize: 18, color: colors.purple, fontWeight: '700' },
  usuarioAvatarWrap: { alignSelf: 'center', marginTop: spacing.xs },
  usuarioAvatar: {
    width: 112,
    height: 112,
    borderRadius: 56,
    backgroundColor: colors.purpleMuted,
    borderWidth: 3,
    borderColor: colors.purpleLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  usuarioAvatarEmoji: { fontSize: 56 },
  usuarioEditBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.purple,
    alignItems: 'center',
    justifyContent: 'center',
  },
  usuarioName: {
    marginTop: spacing.md,
    textAlign: 'center',
    fontSize: 20,
    fontWeight: '700',
    color: colors.purple,
  },
  usuarioLocationRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: spacing.xs,
  },
  usuarioLocationText: { fontSize: 13, color: colors.textSecondary },
  usuarioTagsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginTop: spacing.md,
    paddingHorizontal: spacing.lg,
    columnGap: spacing.sm,
    rowGap: spacing.sm,
  },
  usuarioTagPill: {
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.purple,
    backgroundColor: colors.purpleMuted,
  },
  usuarioTagText: { fontSize: 12, fontWeight: '600', color: colors.purple },
  usuarioStatsRow: { flexDirection: 'row', justifyContent: 'center', marginTop: spacing.xl, columnGap: 56 },
  usuarioStatBlock: { alignItems: 'center' },
  usuarioStatValue: { fontSize: 18, fontWeight: '700', color: colors.purple },
  usuarioStatLabel: { fontSize: 12, color: colors.textSecondary, marginTop: 2 },
  usuarioTrophyBox: {
    marginHorizontal: spacing.lg,
    marginTop: spacing.xl,
    paddingVertical: spacing.xl,
    borderRadius: 12,
    backgroundColor: colors.purpleMuted,
    borderWidth: 1,
    borderColor: colors.purpleLight,
    alignItems: 'center',
  },
  usuarioTrophyEmoji: { fontSize: 40 },
  usuarioTrophyLabel: { marginTop: spacing.sm, fontSize: 14, fontWeight: '600', color: colors.purple },
  usuarioTabBar: {
    flexDirection: 'row',
    marginTop: spacing.xl,
    marginHorizontal: spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: '#eaeaea',
  },
  usuarioTabBtn: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: spacing.sm,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  usuarioTabBtnActive: { borderBottomColor: colors.purple },
  usuarioTabText: { fontSize: 13, fontWeight: '500', color: colors.textSecondary },
  usuarioTabTextActive: { fontWeight: '700', color: colors.purple },
  usuarioFeedSection: { paddingHorizontal: spacing.lg, marginTop: spacing.md, marginBottom: spacing.xl },
  usuarioFeedGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  usuarioFeedCell: {
    width: '31%',
    aspectRatio: 1,
    marginBottom: spacing.sm,
    borderRadius: 6,
    backgroundColor: colors.purpleMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  usuarioFeedCellX: { fontSize: 28, color: colors.purpleLight },
  usuarioFeedCaption: { marginTop: spacing.xs, fontSize: 11, color: colors.textSecondary, textAlign: 'center' },
  usuarioEmptyTab: {
    minHeight: 120,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: spacing.xl,
  },
  usuarioEmptyTabText: { fontSize: 13, color: colors.textSecondary, textAlign: 'center' },
  perfilModalRoot: { flex: 1, justifyContent: 'center', paddingHorizontal: spacing.xl },
  perfilModalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.overlay,
  },
  perfilModalCard: { backgroundColor: colors.white, borderRadius: 16, padding: spacing.lg },
  perfilModalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.purple,
    marginBottom: spacing.sm,
  },
  perfilModalSubtitle: { fontSize: 13, color: '#888', marginBottom: spacing.md },
  perfilModalRow: { paddingVertical: spacing.md, borderTopWidth: 1, borderTopColor: '#eee' },
  perfilModalRowTitle: { fontSize: 15, fontWeight: '600', color: '#333' },
  perfilModalRowHint: { fontSize: 12, color: '#888', marginTop: 2 },
  perfilModalCloseBtn: {
    alignSelf: 'flex-end',
    marginTop: spacing.md,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.lg,
    backgroundColor: colors.purple,
    borderRadius: 8,
  },
  perfilModalCloseText: { fontSize: 14, fontWeight: '600', color: colors.textOnPurple },
  perfilScreenScroll: { flexGrow: 1, padding: spacing.lg, paddingBottom: spacing.xl * 2 },
  perfilSectionTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: colors.purple,
    marginBottom: spacing.md,
    marginTop: spacing.sm,
  },
  perfilFieldLabel: { fontSize: 12, color: '#666', marginBottom: spacing.xs, marginTop: spacing.sm },
  perfilPrimaryBtn: {
    marginTop: spacing.lg,
    height: 48,
    borderRadius: 10,
    backgroundColor: colors.purple,
    alignItems: 'center',
    justifyContent: 'center',
  },
  perfilPrimaryBtnText: { color: colors.white, fontSize: 16, fontWeight: '600' },
  perfilDivider: { height: 1, backgroundColor: '#eee', marginVertical: spacing.lg },
  perfilDangerBtn: {
    marginTop: spacing.md,
    height: 48,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#c62828',
    alignItems: 'center',
    justifyContent: 'center',
  },
  perfilDangerBtnText: { color: '#c62828', fontSize: 16, fontWeight: '600' },
  perfilHint: { fontSize: 12, color: '#888', marginTop: spacing.sm, lineHeight: 18 },
  perfilPrefRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  perfilPrefRowText: { fontSize: 15, color: '#333', flex: 1, paddingRight: spacing.md },
  perfilPrefSub: { fontSize: 12, color: '#888', marginTop: 2 },
  perfilThemeRow: {
    flexDirection: 'row',
    marginTop: spacing.sm,
    columnGap: spacing.sm,
  },
  perfilThemeChip: {
    flex: 1,
    paddingVertical: spacing.sm,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ccc',
    alignItems: 'center',
  },
  perfilThemeChipActive: { borderColor: colors.purple, backgroundColor: '#f3e8ff' },
  perfilThemeChipText: { fontSize: 14, fontWeight: '500', color: '#555' },
  perfilThemeChipTextActive: { color: colors.purple, fontWeight: '700' },
  perfilLegalBlock: { marginBottom: spacing.xl },
  perfilLegalHeading: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.purple,
    marginBottom: spacing.sm,
  },
  perfilLegalParagraph: { fontSize: 14, color: '#444', lineHeight: 22 },
};
