import { colors, spacing } from '../tokens';

export const searchStyles = {
  screen: { flex: 1, backgroundColor: colors.white },
  searchBar: { flexDirection: 'row', margin: spacing.lg, marginTop: spacing.sm, height: 48 },
  backButton: {
    width: 48,
    backgroundColor: colors.purpleMuted,
    borderTopLeftRadius: spacing.sm,
    borderBottomLeftRadius: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchInput: {
    flex: 1,
    backgroundColor: colors.purpleMuted,
    paddingHorizontal: spacing.md,
    fontSize: 16,
  },
  filterButton: {
    width: 48,
    backgroundColor: colors.purpleMuted,
    borderTopRightRadius: spacing.sm,
    borderBottomRightRadius: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionLabel: {
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.xs,
    fontSize: 12,
    fontWeight: '500',
    color: colors.textSecondary,
  },
  listContent: { padding: spacing.lg, gap: spacing.sm },

  userSearchList: {
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.xl * 2,
    gap: spacing.sm,
  },
  userSearchCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    padding: spacing.md,
    gap: spacing.md,
  },
  userSearchAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.purpleMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  userSearchAvatarImage: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.purpleMuted,
  },
  userSearchAvatarText: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.purple,
  },
  userSearchCardBody: { flex: 1, minWidth: 0 },
  userSearchNome: { fontSize: 15, fontWeight: '700', color: colors.textPrimary },
  userSearchMeta: { fontSize: 12, color: colors.textSecondary, marginTop: 2 },
  userSearchEmpty: {
    paddingTop: spacing.xl * 2,
    alignItems: 'center',
    gap: spacing.sm,
  },
  userSearchEmptyText: { fontSize: 13, color: colors.textSecondary },

  conexoesHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  conexoesHeaderTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 17,
    fontWeight: '700',
    color: colors.purple,
  },

  feedBuscaChipsScroll: {
    maxHeight: 44,
    marginBottom: spacing.xs,
  },
  feedBuscaChipsContent: {
    paddingHorizontal: spacing.lg,
    gap: spacing.sm,
    alignItems: 'center',
  },
  feedBuscaSectionTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.purple,
    marginTop: spacing.sm,
    marginBottom: spacing.xs,
    paddingHorizontal: spacing.lg,
  },
  feedBuscaCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    padding: spacing.md,
    gap: spacing.md,
  },
  feedBuscaThumb: {
    width: 48,
    height: 48,
    borderRadius: 10,
    backgroundColor: colors.purpleMuted,
  },
  feedBuscaIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 10,
    backgroundColor: colors.purpleMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  feedBuscaEmoji: { fontSize: 22 },
  feedBuscaModalRoot: {
    flex: 1,
    backgroundColor: colors.overlay,
    justifyContent: 'center',
    padding: spacing.lg,
  },
  feedBuscaModalCard: {
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: spacing.lg,
    overflow: 'hidden',
  },
  feedBuscaModalImage: {
    width: '100%',
    height: 200,
    borderRadius: 12,
    marginBottom: spacing.md,
  },
  feedBuscaModalTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  feedBuscaModalDesc: {
    fontSize: 13,
    color: colors.textSecondary,
    marginTop: spacing.sm,
    lineHeight: 18,
  },
  feedBuscaModalBtn: {
    marginTop: spacing.lg,
    alignSelf: 'center',
    paddingVertical: 10,
    paddingHorizontal: spacing.xl,
    borderRadius: 999,
    backgroundColor: colors.purple,
  },
  feedBuscaModalBtnText: {
    color: colors.textOnPurple,
    fontWeight: '700',
    fontSize: 14,
  },
};
